hash-format = "sha256"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "7d44149b8b22e0b19b082f49809edfc1b5f170e5d1d297cd73ae88c0b432c3ab"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "e12dce3e543168379a2856c66064ee2001e6420a9dfc6163f37b78e518947456"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
hash = "0b5feeae74fe992084ec5cb12eab3404ddd5054e85c9006f7ba4d65f209de13f"
metafile = true

[[files]]
file = "mods/bottle-your-xp.pw.toml"
hash = "d373101fb6e5b01c27b877d2fb334f799da3b27e2c5cd01b2e70ec3246add0f6"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
hash = "0ed502ad7d53ca1936079cb7508b2e085909610ac51337fff2a3ce0fa6dcae28"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "41a3dc271859b118417946d2fdb2408523563b2f4f49048073672a342fb1aebf"
metafile = true

[[files]]
file = "mods/coins-je.pw.toml"
hash = "e907e731cb34d25983960d2dc255f4bc6b20e7fd008a4630ba71264fc6f36fc5"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "d47260d085f9c59609bbc7582968e60f4c476d934c815142360bbcc4b5113a4d"
metafile = true

[[files]]
file = "mods/colorwheel.pw.toml"
hash = "c74b075999921ef7937834c6bb82008cefcb90a6f691208edf708a951c09034c"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "ca80c5f6b0faca95bbc06192a3da36446ff396b5e6e0304f6779269b60bbdd9d"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
hash = "f76188c6e4714a70ea367d7f7a566b05c935a9f19e23f0352f4eb0271a985376"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "8e0ab4317f114231fa313af5fc1b5fadf0e8096d712bdc1fd7359077a003d389"
metafile = true

[[files]]
file = "mods/enchanted-witchcraft.pw.toml"
hash = "2c0b0d01a0b44e140e4235a338c177410122f8dfb6deee2df547a07d0f56f8d7"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "2b7949e506ba69c57139127c0ccc6caf5a9ec5ec97788b81288118db3d7c2ad3"
metafile = true

[[files]]
file = "mods/farmers-delight-refabricated.pw.toml"
hash = "e09385ac1a1c0900b8fa619290eb0f0539949ebbc59f7604a7699485784ccc85"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "adea09f1e1b05da68cf7407992a9391b15985acf5465a888e54ae076dbd543ab"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "21d2df923fa369d69a40d69f6466153146bf403367430eaeb2569c1554857df8"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "cb85864ff2d3936a5ab4f7e7ccf763dbda0153412ba52c95a63b29677a012aaf"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "99efc9e805ce2888680d3cacb9be65733c6d4a8cfcb77e1976205f758db24346"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "d5faaf6d7e4be8bdf9b1b200edee175c2704ce13abad9d1951a4d4a45b432d4e"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
hash = "a51d746fdd98949eb47b83a9da95a1121fd7163601e901d986e57b1d2aca7950"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "b023a335aa5ebb14048587cfef85b374c023518a1db303eb24f1175530ab0085"
metafile = true

[[files]]
file = "mods/kiwi.pw.toml"
hash = "5f2ea40fc2cf14692f1200284104a123e8789adbd868cd29b2ef8ff40b1527f3"
metafile = true

[[files]]
file = "mods/lighting-wand.pw.toml"
hash = "328952e1bb132f708eb4b546b50ed3b9e821257f673383aea19264b2f974b438"
metafile = true

[[files]]
file = "mods/lighty.pw.toml"
hash = "6b986485b44e2007fc69334325f45ad1a4ad1d09d7f7814b1dbc443f171abbd1"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "1ee3c2d6b08bf4c5d7925796244f97f07e826f48ed5696153945a904a5c9030f"
metafile = true

[[files]]
file = "mods/polymer.pw.toml"
hash = "803e0a9f2b35d933bc3d583ce4db52dfff9c717b7f89f4462f0437f16b86e6fc"
metafile = true

[[files]]
file = "mods/smartbrainlib.pw.toml"
hash = "74cf81cd71073f5e4a31ceded3dc5c6220d80bcc25e15f371738b9d720c5a30c"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "ecf8e1df2361e5f1d090f83eee16c449ff1021dfb2da46474a72726406d5d535"
metafile = true

[[files]]
file = "mods/sort-it-out.pw.toml"
hash = "34092a3203271b5554f9deac24c58c6787b4e3df9eb836a8c2f1693841e6320a"
metafile = true

[[files]]
file = "mods/stateobserver.pw.toml"
hash = "946a4e0ac4039f9ed1ee99de0d59a058fe131ee6736716e32b7d72a46dfa1453"
metafile = true

[[files]]
file = "mods/toms-mobs.pw.toml"
hash = "de4b667e3dd966c96c3761c709248fc59636afb2a57cc80ab5116e459bcfc52e"
metafile = true

[[files]]
file = "mods/toms-storage.pw.toml"
hash = "c57e5187ae4382be6c19e596c8a3f4a7a2b4d566c16c6fc8ad8a0629dc9454d1"
metafile = true

[[files]]
file = "mods/toms_storage_create_recipes.pw.toml"
hash = "0092d556d915173f5d9e1fa9b6314ee38cddbacf5b21631e11851c015182f0d8"
metafile = true

[[files]]
file = "mods/travelersbackpack.pw.toml"
hash = "784c9a130f2eb92134e456aee15cf2c5f273af0848640fdddf33d4a7ecad8cbe"
metafile = true
