name = "Minecraft with Fwends!"
author = "patchoulish"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "776d97a69212a14d91dfbd9f064c0effc6ec50f5f5ee10bffe8f3a79e1bc5c58"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
