name = "Minecraft with Fwends!"
author = "marxxengelsbl"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "acc795745d61c41442fb079b8e903f0fc9fa0c10bb199120399d98e1856d225e"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
