name = "minecraft-modpack"
author = "marxxengelsbl"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9187b5230f748815a6e256a5f267199fff1b3a725a729bb33b7680513a6e6308"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
