name = "Minecraft with Fwends!"
author = "patchoulish"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8520b15c16560d473ba33481198ac58312564e15e7f2c56aa1f0d7a9b6faf9bb"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
